### ISSUE TITLE
Program stops responding if last line is a comment

### ISSUE THREAD

**Issue by Cacho-tognax** [PKBeam/shawzin-song-converter#1]
As by title, if the last line of the source file is a comment, the program will hang, forcing me to close the prompt.

I guess I'm maybe making a bigger deal than this is, using this feature and all of that, but hey I think this is the best way to tell you there's a bug with your code(also because I found no contact info) and I don't mind if you don't even want to fix it, just letting you know!

**Comment by PKBeam** [comment]
Fixed, thanks for letting me know.
