### ISSUE TITLE
Shawzin String Invalid

### ISSUE THREAD

**Issue by Dittizardichu** [PKBeam/shawzin-song-converter#2]
As of the newest patch for Warframe, the Shawzin Strings given by your program are invalid. I've tried different scales and tempos and cannot seem to get anything to work.

**Comment by PKBeam** [comment]
Seems like the new patch no longer recognises two (or more) notes playing simultaneously to be valid.

I'll work on fixing this.

Have you tried simple songs that only play one note at at time?
e.g.
```
5
80
A 7/2
G 1/4
A 1/4

F 7/2
E 1/4
F 1/4

G 3/2
G 1/2
G 3/2
F 1/4
G 1/4
```
